### ISSUE TITLE
03.b-validate-metadata.md - UnicodeEncodeError

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-Training/B2FIND-Training#24]
Metadata from fishproject can be validated but the ANDS example gives error:

```sh
./mdmanager.py --mode v -c datacite -s http://oai.datacite.org/oai --mdsubset ANDS.CENTRE-1 --mdprefix oai_dc
|- Run mode:   	Validating
|- Start : 	2018-04-03 10:36:43


|- Validating started : 2018-04-03 10:36:43
CRITICAL :  [CRITICAL] Program is aborted because of a critical error! Description:
CRITICAL :  Traceback (most recent call last):
  File "./mdmanager.py", line 2018, in main
    process(options,pstat)
  File "./mdmanager.py", line 2095, in process
    process_validate(MP,reqlist)
  File "./mdmanager.py", line 2218, in process_validate
    results = MP.validate(request[0],request[3],path,target)
  File "./mdmanager.py", line 1468, in validate
    pvalue=self.is_valid_value(facet,value)
  File "./mdmanager.py", line 1304, in is_valid_value
    vall.append(value.encode("iso-8859-1")) # ashure e.g. display of 'Umlauts' as �,...
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2013' in position 26: ordinal not in range(256)
```

**Comment by chStaiger** [comment]
I still get the same error. In which file does the mapping fail?

**Comment by hwidmann** [comment]
Actually, it all works - at least for me :-)
In the comment above it looks like the sources are not up to date. (the message should no longer come from mdmanager.py but from mapping.py). Please test again and let me know if there is still a problem.

**Comment by chStaiger** [comment]
Did a git pull (July 24th) and executed the master branch software and it works now:

```sh
[admincentos@b2find B2FIND-Training]$ ./mdmanager.py --mode v -c datacite -s http://oai.datacite.org/oai --mdsubset ANDS.CENTRE-1 --mdprefix oai_dc
|- Run mode:   	Validating
|- Start : 	2018-07-24 09:34:07


|- Validating started : 2018-07-24 09:34:07
	 |- Subdirectory ANDS.CENTRE-1 is processed
	 [=                   ] 5 / 10% in 0 sec
	 [===                 ] 14 / 30% in 0 sec
	 [=====               ] 23 / 50% in 0 sec
	 [======              ] 28 / 60% in 0 sec
	 [========            ] 37 / 80% in 0 sec
	 [==========          ] 46 / 100% in 0 sec
   	|- Finished   |@ 09:34:08   |
	| Provided | Validated | Failed |
	|       46 |        46 |      0 |
```
