### ISSUE TITLE
02.b-OAI-harvester.md - harvesting with mdmanager.py

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-Training/B2FIND-Training#8]
```sh
b2find@ubuntu:~/B2FIND-Training$ ./mdmanager.py --mode h -c datacite --source  http://oai.datacite.org/oai --verb ListRecords --mdprefix oai_dc --mdsubset ANDS.CENTRE-1

Version:  	2.0
Run mode:   	Harvesting
Start : 	2016-12-07 11:34:38


|- Harvesting started : 2016-12-07 11:34:38
CRITICAL :  [CRITICAL] Program is aborted because of a critical error! Description:
CRITICAL :  Traceback (most recent call last):
  File "./mdmanager.py", line 1936, in main
    process(options,pstat)
  File "./mdmanager.py", line 1998, in process
    process_harvest(HV,reqlist)
  File "./mdmanager.py", line 2063, in process_harvest
    results = HV.harvest(ir,request)
  File "./mdmanager.py", line 325, in harvest
    ntotrecs=sum(1 for _ in rc)
  File "./mdmanager.py", line 325, in <genexpr>
    ntotrecs=sum(1 for _ in rc)
  File "/usr/local/lib/python2.7/dist-packages/sickle/iterator.py", line 146, in next
    mapped = self.mapper(item)
  File "/usr/local/lib/python2.7/dist-packages/sickle/models.py", line 140, in __init__
    ).getchildren()[0], strip_ns=self._strip_ns)
IndexError: list index out of range
```

**Comment by hwidmann** [comment]
This is fixed with commit b087ad4
